### ISSUE TITLE
PropTypes ➡️ C# classes

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/ui-team-meta#1]
It would be nice if we could generate C# classes from PropTypes so that
1. The backend build breaks on destructive changes
2. We don't have to hand craft C# classes
3. We don't have to manually keep the C# classes up to date

**Comment by Reasonable-Solutions** [comment]
I can imagine that we implement as a babel plugin with babylon. That way it becomes a natural part of the build process. 

 What are good tools for generating C#? @pellebjerkestrand 
Is C# just as impossible to parse as c++? 

otoh,  not parsing but instead having a handful of grep-sed etc over jsx files is probably faster to get out. 

ideally, **F# typeproviders**

**Comment by asbjornh** [comment]
Only problem is that there doesn’t seem to exist any generators from Babel AST to C#

**Comment by Reasonable-Solutions** [comment]
once you have the proptypes out of the ast you can do string concatenation on the C# part. 
Other problem is when you have nested proptypes

**Comment by asbjornh** [comment]
I think propTypes.shape should be OK. You can remove these from their position in the tree and insert them into the program node as a new thing. Not sure about array and arrayOf though

**Comment by asbjornh** [comment]
I'm not so sure about the whole string concatenation part, but I could make an attempt at creating an AST and then you can take over @Reasonable-Solutions ?

**Comment by Reasonable-Solutions** [comment]
string concatenation is the worst. (We all know this, and if we had seen the true nature of string concatenation as a strategy, there would be many things we would consider abhorrent)

The Ast part is probably not much more work than `import babylon; import babel-traverse`. For codegen i'm imagining that the sanest way would be to generate microsoft Bond(tm) AST as json and then run that through gbc somehow.  But Bond is kinda unrelated to our problem innit.

v0v, I am not .net people. Maybe there's a better way.

**Comment by Reasonable-Solutions** [comment]
oh, my dutch .net people gave me this link
https://reubenbond.github.io/posts/codegen-1

**Comment by asbjornh** [comment]
Just for fun I wrote a little thing with babel that turns this:

```js
import Link from 'components/link';

Component.propTypes = {
  array: PropTypes.array,
  text: PropTypes.string,
  bool: PropTypes.bool,
  singleObject: PropTypes.shape({
    property: PropTypes.string
  }),
  objects: PropTypes.arrayOf(
    PropTypes.shape({
      property: PropTypes.string
    })
  ),
  externalType: Link.propTypes,
  externalTypeList: PropTypes.arrayOf(Link.propTypes)
};
```

Into this:

```js
Component = {
  array: array,
  text: string,
  bool: bool,
  singleObject: SingleObject,
  objects: arrayOf(ObjectsItem),
  externalType: Link,
  externalTypeList: arrayOf(Link)
};

SingleObject = {
  property: string
};

ObjectsItem = {
  property: string
};
```
This at least looks more like C# class definitions and may be easier to work with.

My first thought was to try to convert this into typescript interfaces which look more similar to C#, but it doesn't look like babel has builder methods for generating typescript 😐

Not so sure about appending "Item" in `objects: arrayOf(ObjectsItem)` but at least the semantics are a little better than with `objects: arrayOf(Objects)`.

I also thought about reusing propTypes from other components (like `Link` here). I'm not sure how easy it is to generate an import in C#, so maybe an easier alternative is to read and output other components' propTypes as well. This would generate a lot of redundant code though.

**Comment by asbjornh** [comment]
https://github.com/Creuna-Oslo/csharp-class-generator/issues/1

**Comment by pellebjerkestrand** [comment]
Should we close this since work has started and a repo has been made?

**Comment by asbjornh** [comment]
I agree. Closing this.

#2  can remain open or be moved to the new repo.
