### ISSUE TITLE
Create a Creuna theme for mdx-deck

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/ui-team-meta#13]
Please free us from the shackles of Powerpoint ⛓

https://github.com/jxnblk/mdx-deck

**Comment by Reasonable-Solutions** [comment]
I have a talk to prepare, might as well start procrastinating with this task now.

**Comment by pellebjerkestrand** [comment]
Started at https://github.com/Creuna-Oslo/creuna-mal-mdxdeck
