### ISSUE TITLE
New employees should have an overview of tools, services etc.

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/ui-team-meta#16]
As a new employee there are lots of tools, services, programs etc. that one must/should know about.

We should have one or more Markdown files listing these and other resources.

**Comment by pellebjerkestrand** [comment]
I want to add https://github.com/Monica-wo to this as well, but she hasn't accepted the team invitation yet.

**Comment by Reasonable-Solutions** [comment]
fzf https://github.com/junegunn/fzf because bash backwards search is user hostile
nix https://nixos.org/nix/download.html version your project dependencies per project, like node versions and such.
https://github.com/clvv/fasd <- for navigating folders real fast-like

**Comment by dalSara** [comment]
Started on a [draft](https://github.com/Creuna-Oslo/ui-team-meta/tree/issue-%2316/new-employees).
Would not mind some feedback. =)

**Comment by Reasonable-Solutions** [comment]
Everyone needs to know about ssh! 
https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by Reasonable-Solutions** [comment]
@dalSara how is this issue progressing? Has anyone who is not me had a look?

**Comment by dalSara** [comment]
@Reasonable-Solutions no one, that is not you, have had a look as far as I know. 
I have a few more points that is in progress, but have been working on other things this week. Will try to finish and push last changes today.

**Comment by pellebjerkestrand** [comment]
Feel free to push @Atle91 and @monica-wo to contribute as well.

**Comment by dalSara** [comment]
I dont think I have much more to add here. still miss a bit of info, but it is stuff I dont know anything about. Would love to read it if someone else add it.

**Comment by dalSara** [comment]
I dont think I have much more to add here. still miss a bit of info, but it is stuff I dont know anything about. Would love to read it if someone else add it. (Sorry, closed it by misstake.)

**Comment by pellebjerkestrand** [comment]
Make a PR if you feel done 👌🏻

**Comment by Reasonable-Solutions** [comment]
I'll close this. We have a starting point now!
