### ISSUE TITLE
[Tools of Quality] Instrumentation

### ISSUE THREAD

**Issue by Reasonable-Solutions** [Creuna-Oslo/ui-team-meta#28]
I feel that we have gotten a grip on how to do yamlops on Azure now.
Now that we can have the machines do our build and deployments we should add instrumentation.

We could write a thing inhouse or we could use [sentry.io](sentry.io), it is like 26 bucks per month or so.
@pellebjerkestrand I guess you are the person holding the credit cards here. xD

**Comment by pellebjerkestrand** [comment]
I have no credit cards. Multi tenant stuff that we host is a no no to me.

**Comment by Reasonable-Solutions** [comment]
closing this as it seems to be not-our-concern-perhaps-it-happens-per-project
