### ISSUE TITLE
A place to put and show temporary code

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/ui-team-meta#29]
From time to time we are asked to mock frontend things and put it on a server so that clients, designers and people in meetings can look at it.

We should have some place / mechanism for achieving this without having to commit temporary files/components to `develop`/`master` branches.

**Comment by Reasonable-Solutions** [comment]
zeit does this tho
https://twitter.com/zeithq/status/1108840870067998731

**Comment by asbjornh** [comment]
Yes, zeit does this, and you can register for free without supplying payment details. `now` is a sufficient solution to this problem
