### ISSUE TITLE
Status page for GitHub, Travis, npm

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/ui-team-meta#3]
It would be nice to see an overview of what's happening across all our stuff on GitHub, Travis, and npm.

The page should be updated in real time.

Webhooks ➡️ Azure Functions ➡️ Firebase 🤔

**Comment by asbjornh** [comment]
Webhooks ➡️ 🔥base ➡️ 🔥base 🤩

**Comment by asbjornh** [comment]
This has a repo now! https://github.com/Creuna-Oslo/Dashboard/issues/1
