### ISSUE TITLE
Azure access

### ISSUE THREAD

**Issue by Reasonable-Solutions** [Creuna-Oslo/ui-team-meta#32]
It is silly that people on our team can't access azure.
Please check if you can see the creuna stuff on azure and then either ✔️  or comment and mail it@creuna.no

- [ ] @asbjornh 
- [ ] @agarnaas 
- [ ] @mariuswatz 
- [ ] @naivepop 
- [ ] @pellebjerkestrand 
- [ ] @Monica-wo 
- [ ] @serling 
- [ ] @dalSara 
- [ ] @Lkleven 
- [ ] @Reasonable-Solutions 
- [ ] @Atle91

**Comment by pellebjerkestrand** [comment]
What do you mean by "access azure"? There are so many things.

**Comment by Reasonable-Solutions** [comment]
I meant "Microsoft Azure Cloud Computing Platform & Services"
But closing for now.
