### ISSUE TITLE
Headless CMS backed static sites

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/ui-team-meta#7]
We should explore the landscape of headless CMS + static sites to see if we should start building proficiency in this space.

1. Post to build service webhooks from the headless CMS when content changes
2. Pull data from the headless CMS during the static site generation
3. Build (on Travis and/or VSTS?)
4. Hosting on Azure? Something else?

Should we go for self hosted headless CMSes (C#, node?), or SaaS (Contentful, Sanity, Netlify, Strapi etc.)?

**Comment by Reasonable-Solutions** [comment]
I forked back the stuff i threw together using sanity. It is pretty straightforward. 
Closing this as it is older than a year now with no other activity.
