### ISSUE TITLE
A kudos system!

### ISSUE THREAD

**Issue by Reasonable-Solutions** [Creuna-Oslo/ui-team-meta#9]
There could be a system, using the creuna signle-sign-on solution where people get to circle-appreciate each other by getting stickers and some kind of tangible nice thing like a coffee gift card or somtehing.

**Comment by pellebjerkestrand** [comment]
Creuna Cudos ™️

**Comment by Reasonable-Solutions** [comment]
# what if we make a Cudos system? 💻

---

# But what is a Cudos system?

Appreciation is all well and good 😆

---

But what if we could express it to each other with computers? 🤔

With a currency! In a ledger!

---

# The idea 💡

Users get a token every now and then, perhaps regularly, perhaps capped at some number.

the user can spend this token on another user, getting them Cudos(tm) points.
This should have a notification, a friendly message containing what motivated the sudden recognition of a job well done.

Once a user has N Cudos points, they get a physical reward token, like a sticker and a coffee card.

---

# A Scenario

Alice 👩‍💻 is very happy with all the refactoring work Bob 👨‍💻 has been doing on her project, everything is much nicer now.

In order to express her happitude she
 - logs into $SYSTEM
 - Sees that she has enough Cudos-points(tm) to assign one to Bob 👨‍💻
 - Assigns Bob 👨‍💻 a Cudos-point(tm)
 - Sees that her Cudos-points have decreased by one

---

# A Scenario (Cont.)

Ted 👨‍⚖️ just got notified that someone has gotten three kudos points!

He reaches down into his drawer and produces

- an envelope and a pencil
- some tangible reward 🍫

finally he writes an identifier on the envelope with the items and puts it away


---
# A Scenario (Cont.)

The next day Bob 👨‍💻 sits down at the computer machine with a coffee, takes a sip and sees a notification.
Slightly annoyed he proceeds to

- view the notification
- see that he has gotten a total of three Cudos-points from different people all
  with variations of the message "GOOD JOB BOB" attached to them
- and that his cudos reward is waiting for him at the $PICKUP_LOCATION

---

# Can this be MVPed?

  - Small brain: SSO with github and a web interface
  - Normal brain: A slack bot and a dashboard
  - Large brain: A cli app and some endpoints
  - Galaxy brain: Spreadsheets and emails
  - Hypermega brain: Postits

---

**Comment by pellebjerkestrand** [comment]
Closing this, as it's underway.

https://github.com/Creuna-Oslo/KudosBot
